# APPLICATION BROWSER
browser=chrome
# APPLICATION URL
url=https://www.demoblaze.com/
# APPLICATION USERNAME AND PASSWORD
username=ajithm
password=12345678
screenhort=.//Screenshot//
# Details
name=ajithm
country=india
city=chennai
creditcard=12345678009
month=may
year=2026